project:
  type: website
  output-dir: docs

website:
  title: "TripleNexusConsult"

  favicon: img/favicon-32x32.png
  navbar:
    pinned: true
    logo: /img/TripleNexus.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [yeti, custom.scss]
    toc: true
    page-layout: full



